// GENERATED FILE. DO NOT EDIT.
//
// This file was automatically generated by FlutterFire CLI.
// To regenerate, run: flutterfire configure

import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) return web;

    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDuxt6TNKskaPCdeSZSDKeGqSfm92tskt0',
    appId: '1:132582268056:web:d8c359a0be0d6a8aadc4ed',
    messagingSenderId: '132582268056',
    projectId: 'fitcoach-13e40',
    authDomain: 'fitcoach-13e40.firebaseapp.com',
    storageBucket: 'fitcoach-13e40.firebasestorage.app',
    measurementId: 'G-9P46EFYDXV',
  );

  // WEB

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDuQKCuLs6_O3Gwc4W98qljTwfGH3hcSrg',
    appId: '1:132582268056:android:aee7cfce915d635badc4ed',
    messagingSenderId: '132582268056',
    projectId: 'fitcoach-13e40',
    storageBucket: 'fitcoach-13e40.firebasestorage.app',
  );

  // ANDROID

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAR6SZrQrSyE0hxwmMt8KZ8Od59Fxw6Itg',
    appId: '1:132582268056:ios:d70524cd894a6b70adc4ed',
    messagingSenderId: '132582268056',
    projectId: 'fitcoach-13e40',
    storageBucket: 'fitcoach-13e40.firebasestorage.app',
    androidClientId: '132582268056-52nfrourq8puv7ril91p76vpor6ec71b.apps.googleusercontent.com',
    iosClientId: '132582268056-35mvp5g2o46pj0s6ee63e2e2896vb07m.apps.googleusercontent.com',
    iosBundleId: 'com.example.fitcoach',
  );

  // IOS

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAR6SZrQrSyE0hxwmMt8KZ8Od59Fxw6Itg',
    appId: '1:132582268056:ios:d70524cd894a6b70adc4ed',
    messagingSenderId: '132582268056',
    projectId: 'fitcoach-13e40',
    storageBucket: 'fitcoach-13e40.firebasestorage.app',
    androidClientId: '132582268056-52nfrourq8puv7ril91p76vpor6ec71b.apps.googleusercontent.com',
    iosClientId: '132582268056-35mvp5g2o46pj0s6ee63e2e2896vb07m.apps.googleusercontent.com',
    iosBundleId: 'com.example.fitcoach',
  );

  // MACOS

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDuxt6TNKskaPCdeSZSDKeGqSfm92tskt0',
    appId: '1:132582268056:web:a95fa5b41b7e3f99adc4ed',
    messagingSenderId: '132582268056',
    projectId: 'fitcoach-13e40',
    authDomain: 'fitcoach-13e40.firebaseapp.com',
    storageBucket: 'fitcoach-13e40.firebasestorage.app',
    measurementId: 'G-RFBK630E0P',
  );

  // WINDOWS
}